stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - src/cnnClassifier/components/data_ingestion.py  # <--- WATCHING COMPONENT
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/CT-scan-data

  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
      - src/cnnClassifier/components/prepare_base_model.py  # <--- WATCHING COMPONENT
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/cnnClassifier/pipeline/stage_03_model_trainer.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_model_trainer.py
      - src/cnnClassifier/components/model_trainer.py  # <--- WATCHING COMPONENT (Critical for Class Weights)
      - config/config.yaml
      - artifacts/data_ingestion/CT-scan-data
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
      - AUGMENTATION
      - WARMUP_EPOCHS
      - WARMUP_LR
      - FINE_TUNE_EPOCHS
      - FINE_TUNE_LR
      - FINE_TUNE_LAYERS
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/cnnClassifier/pipeline/stage_04_model_evaluation.py
    deps:
      - src/cnnClassifier/pipeline/stage_04_model_evaluation.py
      - src/cnnClassifier/components/model_evaluation_mlflow.py  # <--- WATCHING COMPONENT
      - config/config.yaml
      - artifacts/data_ingestion/CT-scan-data
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false

  ct_gate_training:
    cmd: python src/cnnClassifier/pipeline/stage_05_ct_gate_trainer.py
    deps:
      - src/cnnClassifier/pipeline/stage_05_ct_gate_trainer.py
      - src/cnnClassifier/components/ct_gate_trainer.py  # <--- WATCHING COMPONENT
      - config/config.yaml
      - artifacts/data_ingestion/CT-scan-data
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
      - EPOCHS
      - LEARNING_RATE
    outs:
      - artifacts/ct_gate/ct_gate_model.h5

  days_to_death_training:
    cmd: python src/cnnClassifier/pipeline/stage_06_days_to_death_regression.py
    deps:
      - src/cnnClassifier/pipeline/stage_06_days_to_death_regression.py
      - src/cnnClassifier/components/days_to_death_regressor.py  # <--- WATCHING COMPONENT
      - config/config.yaml
      - artifacts/days_to_death/data
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
      - DTD_EPOCHS
      - DTD_LEARNING_RATE
      - DTD_DROPOUT_RATE
    outs:
      - artifacts/days_to_death/days_to_death_model.h5