AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 10

CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.0001


WARMUP_EPOCHS: 3
FINE_TUNE_EPOCHS: 3
FINE_TUNE_LAYERS: 3

WARMUP_LR: 0.001
FINE_TUNE_LR: 0.00001
